services:
  shell:
    build:
      context: .
      dockerfile: shell/Dockerfile
    container_name: capitalflow-shell
    ports:
      - "8081:80"
    depends_on:
      mfe-analytics:
        condition: service_healthy
      mfe-payments:
        condition: service_healthy
      mfe-transactions:
        condition: service_healthy
    networks:
      - capitalflow-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  mfe-analytics:
    build:
      context: .
      dockerfile: mfe-analytics-react/Dockerfile
    container_name: capitalflow-mfe-analytics
    ports:
      - "8082:80"
    networks:
      - capitalflow-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  mfe-payments:
    build:
      context: .
      dockerfile: mfe-payments/Dockerfile
    container_name: capitalflow-mfe-payments
    ports:
      - "8083:80"
    networks:
      - capitalflow-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  mfe-transactions:
    build:
      context: .
      dockerfile: mfe-transactions/Dockerfile
    container_name: capitalflow-mfe-transactions
    ports:
      - "8084:80"
    networks:
      - capitalflow-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  storybook:
    build:
      context: ./shared-ui
      dockerfile: Dockerfile
    container_name: capitalflow-storybook
    ports:
      - "6007:80"
    networks:
      - capitalflow-net
    restart: unless-stopped

networks:
  capitalflow-net:
    driver: bridge
    name: capitalflow-net
