export const SEARCH_TEST_PAYLOAD =
  '<script>alert("XSS")</script><img src=x onerror=alert("img")>';

export const SEARCH_BACK_LABEL_PREFIX = '<- ';

export const SEARCH_DEMO_I18N_KEYS = {
  PAGE_TITLE: 'ADMIN.DEMOS.SEARCH.PAGE_TITLE',
  PAGE_LEAD: 'ADMIN.DEMOS.SEARCH.PAGE_LEAD',
  PAYLOAD_TITLE: 'ADMIN.DEMOS.SEARCH.PAYLOAD_TITLE',
  INJECT_BUTTON: 'ADMIN.DEMOS.SEARCH.INJECT_BUTTON',
  WITHOUT_MITIGATION: 'ADMIN.DEMOS.SEARCH.WITHOUT_MITIGATION',
  WITH_MITIGATION: 'ADMIN.DEMOS.SEARCH.WITH_MITIGATION',
  FIELD_LABEL: 'ADMIN.DEMOS.SEARCH.FIELD_LABEL',
  FIELD_HINT: 'ADMIN.DEMOS.SEARCH.FIELD_HINT',
  SEARCH_BUTTON: 'ADMIN.DEMOS.SEARCH.SEARCH_BUTTON',
  RESULTS_PREFIX: 'ADMIN.DEMOS.SEARCH.RESULTS_PREFIX',
  NOTE: 'ADMIN.DEMOS.SEARCH.NOTE',
  BACK: 'ADMIN.DEMOS.BACK',
} as const;
