export const PDF_ALLOWED_HOSTS: readonly string[] = [
  'reports.capitalflow.example.com',
  'cdn.capitalflow.example.com',
] as const;

export const PDF_PATH_PATTERN = /^\/reports\/[a-z0-9._-]+\.pdf(\?[a-z0-9=&._-]*)?$/i;
export const PDF_REQUIRED_PROTOCOL = 'https:';

export const PDF_VIEWER_DEFAULT_URL =
  'https://reports.capitalflow.example.com/reports/q1-2026.pdf';

export const PDF_TEST_PAYLOAD = 'javascript:alert("XSS")';

export const PDF_BACK_LABEL_PREFIX = '<- ';

export const PDF_VIEWER_I18N_KEYS = {
  PAGE_TITLE: 'ADMIN.DEMOS.PDF.PAGE_TITLE',
  PAGE_LEAD: 'ADMIN.DEMOS.PDF.PAGE_LEAD',
  PAYLOAD_TITLE: 'ADMIN.DEMOS.PDF.PAYLOAD_TITLE',
  INJECT_BUTTON: 'ADMIN.DEMOS.PDF.INJECT_BUTTON',
  WITHOUT_MITIGATION: 'ADMIN.DEMOS.PDF.WITHOUT_MITIGATION',
  WITH_MITIGATION: 'ADMIN.DEMOS.PDF.WITH_MITIGATION',
  FIELD_LABEL: 'ADMIN.DEMOS.PDF.FIELD_LABEL',
  LOAD_BUTTON: 'ADMIN.DEMOS.PDF.LOAD_BUTTON',
  INVALID_URL: 'ADMIN.DEMOS.PDF.INVALID_URL',
  VALIDATED_HEADER: 'ADMIN.DEMOS.PDF.VALIDATED_HEADER',
  VALIDATED_NOTE: 'ADMIN.DEMOS.PDF.VALIDATED_NOTE',
  HINTS_TITLE: 'ADMIN.DEMOS.PDF.HINTS_TITLE',
  HINT_VALID: 'ADMIN.DEMOS.PDF.HINT_VALID',
  HINT_INVALID_PROTOCOL: 'ADMIN.DEMOS.PDF.HINT_INVALID_PROTOCOL',
  HINT_INVALID_HTTP: 'ADMIN.DEMOS.PDF.HINT_INVALID_HTTP',
  HINT_INVALID_PATH: 'ADMIN.DEMOS.PDF.HINT_INVALID_PATH',
  BACK: 'ADMIN.DEMOS.BACK',
} as const;
